name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set default config
        run: |
          echo '{
            "ignored": [
              ".git",
              "node_modules"
            ]
          }' > $HOME/.treerc
      - name: npm ci
        run: npm ci
      - name: npm test
        run: npm test
      - name: npm run build
        run: npm run build