name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm ci
        run: npm ci
      - name: npm test
        run: npm test
      - name: npm run build
        run: npm run build