name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: package
        run: |
          npm ci
          npm test
          npm run build